fix ci file

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -33,34 +33,34 @@ jobs:
             PACKAGE_ID=$1
             PROJECT_PATH=$2
             echo "Processing package: $PACKAGE_ID"
-
-            # Get the latest version from NuGet
+          
+            # Получаем последнюю версию
             PACKAGE_VERSION=$(curl -s https://api.nuget.org/v3-flatcontainer/${PACKAGE_ID}/index.json | jq -r '.versions[-1]')
             if [ -z "$PACKAGE_VERSION" ]; then
-              echo "No versions found for $PACKAGE_ID. Starting from 1.0.0."
-              NEW_VERSION="1.0.0"
+            echo "No versions found for $PACKAGE_ID. Starting from 1.0.0."
+            NEW_VERSION="1.0.0"
             else
-              echo "Latest version of $PACKAGE_ID: $PACKAGE_VERSION"
-              NEW_VERSION=$(echo $PACKAGE_VERSION | awk -F. -v OFS=. '{$NF++; print}')
+            echo "Latest version of $PACKAGE_ID: $PACKAGE_VERSION"
+            NEW_VERSION=$(echo $PACKAGE_VERSION | awk -F. -v OFS=. '{$NF++; print}')
             fi
             echo "New version: $NEW_VERSION"
-
-            # Update version in .csproj
-            bump_version_in_csproj $PROJECT_PATH $NEW_VERSION
-
-            # Build and pack package
+          
+            # Обновляем версию в .csproj
+            update_version_in_csproj $PROJECT_PATH $NEW_VERSION
+          
+            # Сборка и упаковка
             dotnet build $PROJECT_PATH --configuration Release
             dotnet pack $PROJECT_PATH --configuration Release
-
-            # Determine the output path of the .nupkg file
+          
+            # Определяем путь до .nupkg
             NUPKG_FILE=$(find "$(dirname "$PROJECT_PATH")/bin/Release" -name "*.nupkg" -type f)
             echo "NUPKG File $NUPKG_FILE"
             if [ -z "$NUPKG_FILE" ]; then
-              echo "Error: .nupkg file not found for $PACKAGE_ID"
-              exit 1
+            echo "Error: .nupkg file not found for $PACKAGE_ID"
+            exit 1
             fi
-
-            # Push package to NuGet
+          
+            # Публикуем в NuGet
             dotnet nuget push "$NUPKG_FILE" -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json --skip-duplicate
           }
 
